#!/bin/bash
source admin.cfg

alias ll="ls -FGlahs"
alias ri="ri -f ansi"
alias pcat="pygmentize -f terminal256 -O style=tango -g"
alias hex="openssl rand -hex"
alias path='echo $PATH | tr : "\n" | uniq'
alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"
alias subl="subl -n"
alias h="heroku"
alias c="codeplane"
alias beep='echo -e "\a"'

export ARCHDIR="/dbarchq/"

function tlog {
  if [ ! -f $admin_log ]; then
    touch $admin_log
  fi
  echo "`date +%c` - $1 - $2" >> $admin_log
}
